services:
  api:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 5000:5000
    command: ["gunicorn", "app:app", "-b", "0.0.0.0:5000", "--timeout", "300", "--reload"]
    networks:
      - bot-net
    volumes:
      - ./flask_v2:/flask_v2
      - ./data:/mnt/azure
  bot:
    build: /discord
    environment:
      - API_URL=http://api:5000
      - DISCORD_SERVER_ID=1243870532407922740
    networks:
      - bot-net
networks:
  bot-net: