@startuml
package "SRLIS Assessment Interview" {

start
:Ask about study methods in learning context;
if (Strategies mentioned?) then (no)
    :Probe further, e.g. what to do when having difficulty;
else (yes)
    if (Multiple mentioned?) then (yes)
    :Ask to rate consistency of use for each;
    else (no)
    :Move to next context;
    endif
endif
:Evaluate;
split
:Strategies used;
split again
:Strategy consistency;
split again
:Strategy frequency;
end split
:Predict achievement;
end
}
@enduml