@startuml
[Frontend - Discord Client] as fe

[Backend] as be

cloud {
    [LLM] as llm
}
database "Data Store" as ds {
    folder "Signed up user" {
        [language]
        [start prompt]
        [conversation context]
        [interview outcome]
    }
}

fe -down-> be : 1 user message
be --> ds : 2 store user language +\n store start prompt
be -down-> llm : 3 send prompt(s)
llm ..> be : 4 generated response(s)
be --> be : 5 evaluate response
be --> fe : 6 send next message
@enduml