@startuml
skinparam DefaultFontSize 50

autonumber
participant Frontend
participant API
participant LLM
database PostgreSQL as DB

Frontend -> API: Call start conversation endpoint
API -> DB: Create user records
loop
note over API
 For each conversation step - until interview complete
end note
API -> LLM: Prompt to generate question to ask user
LLM --> API: Question to user
API --> Frontend: Question to user
Frontend -> API: User response
API -> LLM: Prompt to analyse user message and\ndetermine if step complete
LLM --> API: JSON output
group if
note over API, LLM
 If step complete OR abandon step if in progress for  >6 turns
end note
API -> DB: Update conversation state
API -> DB: Store user response and strategy data
note over API, LLM
 Repeat for next step
end note
else else
note over API, LLM
 Repeat for current step
end note
end
end
group When Interview Complete
API -> DB: Retrieve user strategy data
API -> LLM: Prompt to generate summary and suggestions
LLM --> API: Summary
API --> Frontend: Summary
end
@enduml
