apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-volume
  namespace: study-bot
spec:
  storageClassName: managed-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi