"""Store completed contexts as list

Revision ID: 307b082c2f85
Revises: 841928a11380
Create Date: 2024-07-07 11:01:30.410404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307b082c2f85'
down_revision = '841928a11380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_contexts', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_state_completed_contexts_contexts'), 'contexts', ['completed_contexts'], ['id'])
        batch_op.drop_column('last_answered_context')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_answered_context', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_state_completed_contexts_contexts'), type_='foreignkey')
        batch_op.drop_column('completed_contexts')

    # ### end Alembic commands ###
