"""Allow completed contexts to be nullable

Revision ID: 66b3b32b60cd
Revises: 307b082c2f85
Create Date: 2024-07-07 11:09:08.514288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b3b32b60cd'
down_revision = '307b082c2f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.alter_column('completed_contexts',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.alter_column('completed_contexts',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
