"""Add most recent response field

Revision ID: 748966124771
Revises: a368af13b8cb
Create Date: 2024-07-11 19:40:09.631376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748966124771'
down_revision = 'a368af13b8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('most_recent_response', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_column('most_recent_response')

    # ### end Alembic commands ###
