"""Add current context to conversation state

Revision ID: 79cea741613e
Revises: 4190b07fc70c
Create Date: 2024-07-07 11:46:23.205503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79cea741613e'
down_revision = '4190b07fc70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_context', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_state_current_context_contexts'), 'contexts', ['current_context'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_state_current_context_contexts'), type_='foreignkey')
        batch_op.drop_column('current_context')

    # ### end Alembic commands ###
