"""Recreate DB

Revision ID: 8a789400d2b9
Revises: 
Create Date: 2024-06-19 21:37:22.740961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a789400d2b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages'))
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_languages_lang_code'), ['lang_code'], unique=True)

    op.create_table('contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_contexts_language_id_languages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contexts'))
    )
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_strategy_language_id_languages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client', sa.String(length=64), nullable=False),
    sa.Column('language_id', sa.String(length=64), nullable=False),
    sa.Column('message_history', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_users_language_id_languages')),
    sa.PrimaryKeyConstraint('id', 'client', name=op.f('pk_users'))
    )
    op.create_table('interview_answer',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('context', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['context'], ['contexts.id'], name=op.f('fk_interview_answer_context_contexts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_interview_answer_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_answer'))
    )
    op.create_table('state',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('interview_completed', sa.Boolean(), nullable=False),
    sa.Column('last_answered_context', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_state_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_state'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state')
    op.drop_table('interview_answer')
    op.drop_table('users')
    op.drop_table('strategy')
    op.drop_table('contexts')
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_languages_lang_code'))

    op.drop_table('languages')
    # ### end Alembic commands ###
