"""Cascade delete user conversation elements

Revision ID: a368af13b8cb
Revises: 966da95e961d
Create Date: 2024-07-07 17:22:34.599042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a368af13b8cb'
down_revision = '966da95e961d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_completed_contexts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversation_completed_contexts_conversation_id_state', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_conversation_completed_contexts_conversation_id_state'), 'state', ['conversation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_interview_answer_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_interview_answer_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint('fk_state_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_state_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_state_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_state_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_interview_answer_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_interview_answer_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('conversation_completed_contexts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_conversation_completed_contexts_conversation_id_state'), type_='foreignkey')
        batch_op.create_foreign_key('fk_conversation_completed_contexts_conversation_id_state', 'state', ['conversation_id'], ['id'])

    # ### end Alembic commands ###
