"""users table

Revision ID: c43fe625a844
Revises: 
Create Date: 2024-06-05 21:15:18.267528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43fe625a844'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_languages_lang_code'), ['lang_code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client', sa.String(length=64), nullable=False),
    sa.Column('language_id', sa.String(length=64), nullable=False),
    sa.Column('message_history', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id', 'client')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_languages_lang_code'))

    op.drop_table('languages')
    # ### end Alembic commands ###
