"""Completed context nullable

Revision ID: fd4a6c4d9705
Revises: b3c61141452c
Create Date: 2024-07-07 15:46:44.836631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4a6c4d9705'
down_revision = 'b3c61141452c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contexts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.String(length=64), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_contexts_parent_id_state'), 'state', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contexts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contexts_parent_id_state'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
