"""Delete link back from context

Revision ID: 4106e2fdf568
Revises: aa1eeade238b
Create Date: 2024-07-07 15:53:07.263768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4106e2fdf568'
down_revision = 'aa1eeade238b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contexts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contexts_parent_id_state', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contexts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.VARCHAR(length=64), nullable=False))
        batch_op.create_foreign_key('fk_contexts_parent_id_state', 'state', ['parent_id'], ['id'])

    # ### end Alembic commands ###
