"""Add user message text to interview answer

Revision ID: 4190b07fc70c
Revises: 66b3b32b60cd
Create Date: 2024-07-07 11:40:20.211903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4190b07fc70c'
down_revision = '66b3b32b60cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
