"""Make frequency nullable

Revision ID: 47fec5473552
Revises: 4fa954a251b6
Create Date: 2024-07-11 20:35:23.154762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fec5473552'
down_revision = '4fa954a251b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
