"""Add frequency to interview answer

Revision ID: 4fa954a251b6
Revises: 748966124771
Create Date: 2024-07-11 20:23:29.491302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa954a251b6'
down_revision = '748966124771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###
