"""Add separate user_strategies table

Revision ID: 586d35dd0a91
Revises: cfd2101d3327
Create Date: 2024-08-04 16:19:40.481858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586d35dd0a91'
down_revision = 'cfd2101d3327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_strategy',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_client', sa.String(length=64), nullable=False),
    sa.Column('context', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['context'], ['contexts.id'], name=op.f('fk_user_strategy_context_contexts')),
    sa.ForeignKeyConstraint(['strategy'], ['strategy.id'], name=op.f('fk_user_strategy_strategy_strategy')),
    sa.ForeignKeyConstraint(['user_id', 'user_client'], ['users.id', 'users.client'], name=op.f('fk_user_strategy_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_strategy'))
    )
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.alter_column('context',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_interview_answer_strategy_strategy', type_='foreignkey')
        batch_op.drop_column('frequency')
        batch_op.drop_column('strategy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('frequency', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_interview_answer_strategy_strategy', 'strategy', ['strategy'], ['id'])
        batch_op.alter_column('context',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('user_strategy')
    # ### end Alembic commands ###
