"""Correct DB setup

Revision ID: 64b27bbbcbf1
Revises: 8a789400d2b9
Create Date: 2024-06-19 21:49:08.394804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b27bbbcbf1'
down_revision = '8a789400d2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategies', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_interview_answer_strategies_strategy'), 'strategy', ['strategies'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_interview_answer_strategies_strategy'), type_='foreignkey')
        batch_op.drop_column('strategies')

    # ### end Alembic commands ###
