"""Make SU boolean

Revision ID: 721cac364a89
Revises: 5c4b7b8bc45e
Create Date: 2024-08-08 19:05:59.553096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721cac364a89'
down_revision = '5c4b7b8bc45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_evaluation', schema=None) as batch_op:
        batch_op.alter_column('SU',
               existing_type=sa.FLOAT(),
               type_=sa.Boolean(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_evaluation', schema=None) as batch_op:
        batch_op.alter_column('SU',
               existing_type=sa.Boolean(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
