"""Add strategy description

Revision ID: 841928a11380
Revises: 64b27bbbcbf1
Create Date: 2024-07-03 20:36:34.123667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841928a11380'
down_revision = '64b27bbbcbf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
