"""add back current context

Revision ID: 966da95e961d
Revises: affb3c565c8e
Create Date: 2024-07-07 16:55:49.549088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966da95e961d'
down_revision = 'affb3c565c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_context', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_state_current_context_contexts'), 'contexts', ['current_context'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_state_current_context_contexts'), type_='foreignkey')
        batch_op.drop_column('current_context')

    # ### end Alembic commands ###
