"""Link things to user correctly

Revision ID: a3c2a4a78798
Revises: 47fec5473552
Create Date: 2024-07-13 20:24:54.183927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c2a4a78798'
down_revision = '47fec5473552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_response',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_client', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('message_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'user_client'], ['users.id', 'users.client'], name=op.f('fk_llm_response_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_response'))
    )
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_client', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('strategy', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_interview_answer_strategies_strategy', type_='foreignkey')
        batch_op.drop_constraint('fk_interview_answer_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_interview_answer_user_id_users'), 'users', ['user_id', 'user_client'], ['id', 'client'])
        batch_op.create_foreign_key(batch_op.f('fk_interview_answer_strategy_strategy'), 'strategy', ['strategy'], ['id'])
        batch_op.drop_column('strategies')

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_client', sa.String(length=64), nullable=False))
        batch_op.drop_constraint('fk_state_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_state_user_id_users'), 'users', ['user_id', 'user_client'], ['id', 'client'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_state_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_state_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_client')

    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategies', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_interview_answer_strategy_strategy'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_interview_answer_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_interview_answer_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_interview_answer_strategies_strategy', 'strategy', ['strategies'], ['id'])
        batch_op.drop_column('strategy')
        batch_op.drop_column('user_client')

    op.drop_table('llm_response')
    # ### end Alembic commands ###
