"""Multiple joins between state and context

Revision ID: aa1eeade238b
Revises: fd4a6c4d9705
Create Date: 2024-07-07 15:51:46.533705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1eeade238b'
down_revision = 'fd4a6c4d9705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_context_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_context_ids', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_state_current_context_contexts', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_state_completed_context_ids_contexts'), 'contexts', ['completed_context_ids'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_state_current_context_id_contexts'), 'contexts', ['current_context_id'], ['id'])
        batch_op.drop_column('current_context')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_context', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_state_current_context_id_contexts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_state_completed_context_ids_contexts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_state_current_context_contexts', 'contexts', ['current_context'], ['id'])
        batch_op.drop_column('completed_context_ids')
        batch_op.drop_column('current_context_id')

    # ### end Alembic commands ###
