"""User unique constraint

Revision ID: af267bb37cfc
Revises: 721cac364a89
Create Date: 2024-08-10 11:33:29.779962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af267bb37cfc'
down_revision = '721cac364a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_client_uc', ['id', 'client'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('_user_client_uc', type_='unique')

    # ### end Alembic commands ###
