"""state-context assoc table 3

Revision ID: affb3c565c8e
Revises: f23818c669a4
Create Date: 2024-07-07 16:50:24.686376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affb3c565c8e'
down_revision = 'f23818c669a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_completed_contexts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.String(length=64), nullable=False))
        batch_op.drop_constraint('fk_conversation_completed_contexts_conversation_state', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_conversation_completed_contexts_conversation_id_state'), 'state', ['conversation_id'], ['id'])
        batch_op.drop_column('conversation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_completed_contexts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_conversation_completed_contexts_conversation_id_state'), type_='foreignkey')
        batch_op.create_foreign_key('fk_conversation_completed_contexts_conversation_state', 'state', ['conversation'], ['id'])
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###
