"""Completed contexts child relationship

Revision ID: b3c61141452c
Revises: 79cea741613e
Create Date: 2024-07-07 14:08:49.003018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c61141452c'
down_revision = '79cea741613e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint('fk_state_completed_contexts_contexts', type_='foreignkey')
        batch_op.drop_column('completed_contexts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_contexts', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_state_completed_contexts_contexts', 'contexts', ['completed_contexts'], ['id'])

    # ### end Alembic commands ###
