"""make context and strategy nullable in interviewanswer

Revision ID: cfd2101d3327
Revises: f23183488e5d
Create Date: 2024-08-01 20:15:33.423001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd2101d3327'
down_revision = 'f23183488e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.alter_column('context',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('strategy',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.alter_column('strategy',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('context',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
