"""Update user_strategies table

Revision ID: f0c885595069
Revises: 586d35dd0a91
Create Date: 2024-08-04 16:33:57.823416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c885595069'
down_revision = '586d35dd0a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_strategy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_answer_id', sa.String(length=64), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_user_strategy_interview_answer_id_interview_answer'), 'interview_answer', ['interview_answer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_strategy', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_strategy_interview_answer_id_interview_answer'), type_='foreignkey')
        batch_op.drop_column('interview_answer_id')

    # ### end Alembic commands ###
