"""Add timestamp to user replies

Revision ID: f23183488e5d
Revises: a3c2a4a78798
Create Date: 2024-07-31 21:28:04.471492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23183488e5d'
down_revision = 'a3c2a4a78798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_answer', schema=None) as batch_op:
        batch_op.drop_column('message_time')

    # ### end Alembic commands ###
