"""state-context assoc table 3

Revision ID: f23818c669a4
Revises: 4106e2fdf568
Create Date: 2024-07-07 16:48:44.558799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23818c669a4'
down_revision = '4106e2fdf568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_completed_contexts',
    sa.Column('conversation', sa.String(length=64), nullable=False),
    sa.Column('completed_context_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['completed_context_id'], ['contexts.id'], name=op.f('fk_conversation_completed_contexts_completed_context_id_contexts')),
    sa.ForeignKeyConstraint(['conversation'], ['state.id'], name=op.f('fk_conversation_completed_contexts_conversation_state')),
    sa.PrimaryKeyConstraint('conversation', 'completed_context_id', name=op.f('pk_conversation_completed_contexts'))
    )
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint('fk_state_completed_context_ids_contexts', type_='foreignkey')
        batch_op.drop_constraint('fk_state_current_context_id_contexts', type_='foreignkey')
        batch_op.drop_column('completed_context_ids')
        batch_op.drop_column('current_context_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_context_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('completed_context_ids', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_state_current_context_id_contexts', 'contexts', ['current_context_id'], ['id'])
        batch_op.create_foreign_key('fk_state_completed_context_ids_contexts', 'contexts', ['completed_context_ids'], ['id'])

    op.drop_table('conversation_completed_contexts')
    # ### end Alembic commands ###
